### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by amras0000** [zenzoa/bunbons#2]
Hello! Loving the game.

I am running into performance issues. If I keep interacting with the game for about 20 minutes, it starts to hog processor cycles and overwhelm one of my cores, so the audio gets distorted. There's also a slight increase in memory usage over time, though that might be unrelated.
When I refresh the page and restart the game, CPU and memory usage both drop and the audio is fixed, but after some time the issue appears again.

A way to reproduce this issue:
- start the game, and create a planet with one bunbon (plus possibly some food and toys, so the bunbon isn't sad)
- click on the bunbon several thousand times (ex. with an autoclicker)
- observe how the CPU usage of the game increases over time, and eventually the sound quality degrades.
- observe how switching to another planet or moving the bunbon into storage does not improve the performance of the game
- refresh the page, and start the game again
- observe that the CPU usage is back to normal.

EDIT: added reproduction steps

**Comment by zenzoa** [comment]
Thanks so much for the detailed (and compassionate to the bunbon) repro steps! I've had a heck of a time trying to debug these performance issues, but your idea of using an autoclicker might let me zero-in on where the memory leak is happening.

**Comment by amras0000** [comment]
I had more of a look at the code this morning and performed one more test:
There are no performance issues when the game is muted.

For some reason, every time a sound effect is played, even if it's stopped later, the resource usage of the game permanently increases.

Just adding this to mousePressed produced the same issues:
```javascript
for (let i=0; i<100; i++) {
    soundEffects['click-bunbon'].play()
    soundEffects['click-bunbon'].stop()
}
```

**Comment by amras0000** [comment]
In other words,
make sure to call
```javascript
soundEffects['...'].close()
```
before you try to play that effect again.

**Comment by zenzoa** [comment]
Thanks for pinpointing the issue. [p5 doesn't have a close() function](https://p5js.org/reference/#/libraries/p5.sound) unfortunately. Interestingly, in Firefox, the audio distortion doesn't happen for me - even if I play 1000 sound effects in a loop, it mostly clears up after a few seconds. Maybe it just takes more to get it to happen in Firefox, but I can get it to happen easily in Chrome/Edge. Diving deeper to see if there's a workaround or known issue.

EDIT: Oh huh it's an [existing issue](https://github.com/processing/p5.js-sound/issues/647) *that I commented on* xD

EDIT 2: Some suggested in a [related bug](https://github.com/processing/p5.js-sound/issues/494) that reverting to an older version of p5-sound would work, but that doesn't solve it for me.

**Comment by zenzoa** [comment]
Switched over to using HTML Audio elements instead of p5 sound. I hope this solves the problem? Because browsers block autoplay until you click something, I've had to start the game muted - but I want to make a splash screen you click through to solve that in a more elegant way.
